#############################################################################
# Makefile for building: brdf
# Generated by qmake (3.1) (Qt 5.14.1)
# Project:  BRDF.pro
# Template: app
# Command: /home/rapido/Qt/5.14.1/gcc_64/bin/qmake -o Makefile BRDF.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_QML_DEBUG -DQT_OPENGL_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_XML_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g -Wall -Wextra -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -std=c++11 -g -Wall -Wextra -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I. -I../libigl/include -I../libigl/external/eigen -isystem /usr/local/include/opencv4/opencv2 -isystem /usr/local/include/opencv4 -I/usr/local/lib -I../../Qt/5.14.1/gcc_64/include -I../../Qt/5.14.1/gcc_64/include/QtOpenGL -I../../Qt/5.14.1/gcc_64/include/QtWidgets -I../../Qt/5.14.1/gcc_64/include/QtGui -I../../Qt/5.14.1/gcc_64/include/QtXml -I../../Qt/5.14.1/gcc_64/include/QtCore -I. -isystem /usr/include/libdrm -I../../Qt/5.14.1/gcc_64/mkspecs/linux-g++
QMAKE         = /home/rapido/Qt/5.14.1/gcc_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /home/rapido/Qt/5.14.1/gcc_64/bin/qmake -install qinstall
QINSTALL_PROGRAM = /home/rapido/Qt/5.14.1/gcc_64/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = brdf1.0.0
DISTDIR = /home/rapido/Catriona/BRDF/.tmp/brdf1.0.0
LINK          = g++
LFLAGS        = -Wl,-rpath,/home/rapido/Qt/5.14.1/gcc_64/lib
LIBS          = $(SUBLIBS) -L /usr/local/lib/ -l:libopencv_core.so.4.3 -l:libopencv_imgproc.so.4.3 -l:libopencv_imgcodecs.so.4.3 -l:libopencv_highgui.so.4.3 /home/rapido/Catriona/BRDF/levmar/liblevmar.a -lstdc++ -lglut -lGLU -lopenblas /home/rapido/Qt/5.14.1/gcc_64/lib/libQt5OpenGL.so /home/rapido/Qt/5.14.1/gcc_64/lib/libQt5Widgets.so /home/rapido/Qt/5.14.1/gcc_64/lib/libQt5Gui.so /home/rapido/Qt/5.14.1/gcc_64/lib/libQt5Xml.so /home/rapido/Qt/5.14.1/gcc_64/lib/libQt5Core.so -lGL -lpthread   
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = brdfdata.cpp \
		glutcallbacks.cpp \
		main.cpp 
OBJECTS       = brdfdata.o \
		glutcallbacks.o \
		main.o
DIST          = ../../Qt/5.14.1/gcc_64/mkspecs/features/spec_pre.prf \
		../../Qt/5.14.1/gcc_64/mkspecs/common/unix.conf \
		../../Qt/5.14.1/gcc_64/mkspecs/common/linux.conf \
		../../Qt/5.14.1/gcc_64/mkspecs/common/sanitize.conf \
		../../Qt/5.14.1/gcc_64/mkspecs/common/gcc-base.conf \
		../../Qt/5.14.1/gcc_64/mkspecs/common/gcc-base-unix.conf \
		../../Qt/5.14.1/gcc_64/mkspecs/common/g++-base.conf \
		../../Qt/5.14.1/gcc_64/mkspecs/common/g++-unix.conf \
		../../Qt/5.14.1/gcc_64/mkspecs/qconfig.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_3danimation.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_3danimation_private.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dextras.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dquickanimation.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_3drender.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_bodymovin_private.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_charts.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_charts_private.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_core.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_datavisualization.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_edid_support_private.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_egl_support_private.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_gamepad.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_glx_support_private.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_help.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_input_support_private.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_kms_support_private.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_location.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_location_private.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_multimediagsttools_private.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_network.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_networkauth.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_networkauth_private.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_positioningquick.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_positioningquick_private.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_purchasing.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_qmlmodels.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_quick3d.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_quick3d_private.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_quick3dassetimport.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_quick3dassetimport_private.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_quick3drender.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_quick3drender_private.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_quick3druntimerender.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_quick3druntimerender_private.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_quick3dutils.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_quick3dutils_private.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_quickshapes_private.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_quicktemplates2.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_remoteobjects.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_repparser.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_repparser_private.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_script.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_script_private.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_scxml.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_scxml_private.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_serialbus.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_service_support_private.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_texttospeech.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_waylandclient.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_waylandclient_private.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_waylandcompositor.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_waylandcompositor_private.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_webengine.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_webview.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/features/qt_functions.prf \
		../../Qt/5.14.1/gcc_64/mkspecs/features/qt_config.prf \
		../../Qt/5.14.1/gcc_64/mkspecs/linux-g++/qmake.conf \
		../../Qt/5.14.1/gcc_64/mkspecs/features/spec_post.prf \
		../../Qt/5.14.1/gcc_64/mkspecs/features/exclusive_builds.prf \
		../../Qt/5.14.1/gcc_64/mkspecs/features/toolchain.prf \
		../../Qt/5.14.1/gcc_64/mkspecs/features/default_pre.prf \
		../../Qt/5.14.1/gcc_64/mkspecs/features/resolve_config.prf \
		../../Qt/5.14.1/gcc_64/mkspecs/features/default_post.prf \
		../../Qt/5.14.1/gcc_64/mkspecs/features/qml_debug.prf \
		../../Qt/5.14.1/gcc_64/mkspecs/features/warn_on.prf \
		../../Qt/5.14.1/gcc_64/mkspecs/features/qt.prf \
		../../Qt/5.14.1/gcc_64/mkspecs/features/resources_functions.prf \
		../../Qt/5.14.1/gcc_64/mkspecs/features/resources.prf \
		../../Qt/5.14.1/gcc_64/mkspecs/features/moc.prf \
		../../Qt/5.14.1/gcc_64/mkspecs/features/unix/opengl.prf \
		../../Qt/5.14.1/gcc_64/mkspecs/features/uic.prf \
		../../Qt/5.14.1/gcc_64/mkspecs/features/unix/thread.prf \
		../../Qt/5.14.1/gcc_64/mkspecs/features/qmake_use.prf \
		../../Qt/5.14.1/gcc_64/mkspecs/features/file_copies.prf \
		../../Qt/5.14.1/gcc_64/mkspecs/features/testcase_targets.prf \
		../../Qt/5.14.1/gcc_64/mkspecs/features/exceptions.prf \
		../../Qt/5.14.1/gcc_64/mkspecs/features/yacc.prf \
		../../Qt/5.14.1/gcc_64/mkspecs/features/lex.prf \
		BRDF.pro brdfdata.h \
		glutcallbacks.h \
		glut.h \
		glext.h brdfdata.cpp \
		glutcallbacks.cpp \
		main.cpp
QMAKE_TARGET  = brdf
DESTDIR       = 
TARGET        = brdf


first: all
####### Build rules

brdf:  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: BRDF.pro ../../Qt/5.14.1/gcc_64/mkspecs/linux-g++/qmake.conf ../../Qt/5.14.1/gcc_64/mkspecs/features/spec_pre.prf \
		../../Qt/5.14.1/gcc_64/mkspecs/common/unix.conf \
		../../Qt/5.14.1/gcc_64/mkspecs/common/linux.conf \
		../../Qt/5.14.1/gcc_64/mkspecs/common/sanitize.conf \
		../../Qt/5.14.1/gcc_64/mkspecs/common/gcc-base.conf \
		../../Qt/5.14.1/gcc_64/mkspecs/common/gcc-base-unix.conf \
		../../Qt/5.14.1/gcc_64/mkspecs/common/g++-base.conf \
		../../Qt/5.14.1/gcc_64/mkspecs/common/g++-unix.conf \
		../../Qt/5.14.1/gcc_64/mkspecs/qconfig.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_3danimation.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_3danimation_private.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dextras.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dquickanimation.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_3drender.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_bodymovin_private.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_charts.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_charts_private.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_core.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_datavisualization.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_edid_support_private.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_egl_support_private.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_gamepad.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_glx_support_private.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_help.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_input_support_private.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_kms_support_private.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_location.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_location_private.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_multimediagsttools_private.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_network.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_networkauth.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_networkauth_private.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_positioningquick.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_positioningquick_private.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_purchasing.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_qmlmodels.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_quick3d.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_quick3d_private.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_quick3dassetimport.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_quick3dassetimport_private.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_quick3drender.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_quick3drender_private.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_quick3druntimerender.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_quick3druntimerender_private.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_quick3dutils.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_quick3dutils_private.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_quickshapes_private.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_quicktemplates2.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_remoteobjects.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_repparser.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_repparser_private.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_script.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_script_private.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_scxml.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_scxml_private.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_serialbus.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_service_support_private.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_texttospeech.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_waylandclient.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_waylandclient_private.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_waylandcompositor.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_waylandcompositor_private.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_webengine.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_webview.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../Qt/5.14.1/gcc_64/mkspecs/features/qt_functions.prf \
		../../Qt/5.14.1/gcc_64/mkspecs/features/qt_config.prf \
		../../Qt/5.14.1/gcc_64/mkspecs/linux-g++/qmake.conf \
		../../Qt/5.14.1/gcc_64/mkspecs/features/spec_post.prf \
		../../Qt/5.14.1/gcc_64/mkspecs/features/exclusive_builds.prf \
		../../Qt/5.14.1/gcc_64/mkspecs/features/toolchain.prf \
		../../Qt/5.14.1/gcc_64/mkspecs/features/default_pre.prf \
		../../Qt/5.14.1/gcc_64/mkspecs/features/resolve_config.prf \
		../../Qt/5.14.1/gcc_64/mkspecs/features/default_post.prf \
		../../Qt/5.14.1/gcc_64/mkspecs/features/qml_debug.prf \
		../../Qt/5.14.1/gcc_64/mkspecs/features/warn_on.prf \
		../../Qt/5.14.1/gcc_64/mkspecs/features/qt.prf \
		../../Qt/5.14.1/gcc_64/mkspecs/features/resources_functions.prf \
		../../Qt/5.14.1/gcc_64/mkspecs/features/resources.prf \
		../../Qt/5.14.1/gcc_64/mkspecs/features/moc.prf \
		../../Qt/5.14.1/gcc_64/mkspecs/features/unix/opengl.prf \
		../../Qt/5.14.1/gcc_64/mkspecs/features/uic.prf \
		../../Qt/5.14.1/gcc_64/mkspecs/features/unix/thread.prf \
		../../Qt/5.14.1/gcc_64/mkspecs/features/qmake_use.prf \
		../../Qt/5.14.1/gcc_64/mkspecs/features/file_copies.prf \
		../../Qt/5.14.1/gcc_64/mkspecs/features/testcase_targets.prf \
		../../Qt/5.14.1/gcc_64/mkspecs/features/exceptions.prf \
		../../Qt/5.14.1/gcc_64/mkspecs/features/yacc.prf \
		../../Qt/5.14.1/gcc_64/mkspecs/features/lex.prf \
		BRDF.pro
	$(QMAKE) -o Makefile BRDF.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug
../../Qt/5.14.1/gcc_64/mkspecs/features/spec_pre.prf:
../../Qt/5.14.1/gcc_64/mkspecs/common/unix.conf:
../../Qt/5.14.1/gcc_64/mkspecs/common/linux.conf:
../../Qt/5.14.1/gcc_64/mkspecs/common/sanitize.conf:
../../Qt/5.14.1/gcc_64/mkspecs/common/gcc-base.conf:
../../Qt/5.14.1/gcc_64/mkspecs/common/gcc-base-unix.conf:
../../Qt/5.14.1/gcc_64/mkspecs/common/g++-base.conf:
../../Qt/5.14.1/gcc_64/mkspecs/common/g++-unix.conf:
../../Qt/5.14.1/gcc_64/mkspecs/qconfig.pri:
../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_3danimation.pri:
../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_3danimation_private.pri:
../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dcore.pri:
../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri:
../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dextras.pri:
../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dextras_private.pri:
../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dinput.pri:
../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri:
../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri:
../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dquick.pri:
../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri:
../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dquickanimation.pri:
../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dquickextras.pri:
../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dquickextras_private.pri:
../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dquickinput.pri:
../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dquickinput_private.pri:
../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dquickrender.pri:
../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dquickrender_private.pri:
../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d.pri:
../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_3drender.pri:
../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_3drender_private.pri:
../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_accessibility_support_private.pri:
../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri:
../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_bodymovin_private.pri:
../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_charts.pri:
../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_charts_private.pri:
../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_concurrent.pri:
../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_core.pri:
../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_core_private.pri:
../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_datavisualization.pri:
../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_datavisualization_private.pri:
../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_dbus.pri:
../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri:
../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_designer.pri:
../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_designer_private.pri:
../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_edid_support_private.pri:
../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_egl_support_private.pri:
../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_fb_support_private.pri:
../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_gamepad.pri:
../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_gamepad_private.pri:
../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_glx_support_private.pri:
../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_gui.pri:
../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_gui_private.pri:
../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_help.pri:
../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_help_private.pri:
../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_input_support_private.pri:
../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_kms_support_private.pri:
../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_location.pri:
../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_location_private.pri:
../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_multimedia.pri:
../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri:
../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_multimediagsttools_private.pri:
../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_network.pri:
../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_network_private.pri:
../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_networkauth.pri:
../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_networkauth_private.pri:
../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_nfc.pri:
../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri:
../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_opengl.pri:
../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri:
../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri:
../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_packetprotocol_private.pri:
../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_positioning.pri:
../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri:
../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_positioningquick.pri:
../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_positioningquick_private.pri:
../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_printsupport.pri:
../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_purchasing.pri:
../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_purchasing_private.pri:
../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_qml.pri:
../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_qml_private.pri:
../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_qmldebug_private.pri:
../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_qmlmodels.pri:
../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_qmlmodels_private.pri:
../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_qmltest.pri:
../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_qmlworkerscript.pri:
../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_qmlworkerscript_private.pri:
../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_quick.pri:
../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_quick3d.pri:
../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_quick3d_private.pri:
../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_quick3dassetimport.pri:
../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_quick3dassetimport_private.pri:
../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_quick3drender.pri:
../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_quick3drender_private.pri:
../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_quick3druntimerender.pri:
../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_quick3druntimerender_private.pri:
../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_quick3dutils.pri:
../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_quick3dutils_private.pri:
../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_quick_private.pri:
../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_quickcontrols2.pri:
../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_quickshapes_private.pri:
../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_quicktemplates2.pri:
../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri:
../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_remoteobjects.pri:
../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_remoteobjects_private.pri:
../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_repparser.pri:
../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_repparser_private.pri:
../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_script.pri:
../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_script_private.pri:
../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_scripttools.pri:
../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri:
../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_scxml.pri:
../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_scxml_private.pri:
../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_sensors.pri:
../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri:
../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_serialbus.pri:
../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_serialbus_private.pri:
../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_serialport.pri:
../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri:
../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_service_support_private.pri:
../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_sql.pri:
../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_sql_private.pri:
../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_svg.pri:
../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_svg_private.pri:
../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_testlib.pri:
../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri:
../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_texttospeech.pri:
../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_texttospeech_private.pri:
../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_theme_support_private.pri:
../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri:
../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_uitools.pri:
../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri:
../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_virtualkeyboard.pri:
../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_virtualkeyboard_private.pri:
../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_vulkan_support_private.pri:
../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_waylandclient.pri:
../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_waylandclient_private.pri:
../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_waylandcompositor.pri:
../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_waylandcompositor_private.pri:
../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_webchannel.pri:
../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri:
../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_webengine.pri:
../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri:
../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri:
../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri:
../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri:
../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_websockets.pri:
../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri:
../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_webview.pri:
../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_webview_private.pri:
../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_widgets.pri:
../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri:
../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_x11extras.pri:
../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri:
../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_xkbcommon_support_private.pri:
../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_xml.pri:
../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_xml_private.pri:
../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../Qt/5.14.1/gcc_64/mkspecs/features/qt_functions.prf:
../../Qt/5.14.1/gcc_64/mkspecs/features/qt_config.prf:
../../Qt/5.14.1/gcc_64/mkspecs/linux-g++/qmake.conf:
../../Qt/5.14.1/gcc_64/mkspecs/features/spec_post.prf:
../../Qt/5.14.1/gcc_64/mkspecs/features/exclusive_builds.prf:
../../Qt/5.14.1/gcc_64/mkspecs/features/toolchain.prf:
../../Qt/5.14.1/gcc_64/mkspecs/features/default_pre.prf:
../../Qt/5.14.1/gcc_64/mkspecs/features/resolve_config.prf:
../../Qt/5.14.1/gcc_64/mkspecs/features/default_post.prf:
../../Qt/5.14.1/gcc_64/mkspecs/features/qml_debug.prf:
../../Qt/5.14.1/gcc_64/mkspecs/features/warn_on.prf:
../../Qt/5.14.1/gcc_64/mkspecs/features/qt.prf:
../../Qt/5.14.1/gcc_64/mkspecs/features/resources_functions.prf:
../../Qt/5.14.1/gcc_64/mkspecs/features/resources.prf:
../../Qt/5.14.1/gcc_64/mkspecs/features/moc.prf:
../../Qt/5.14.1/gcc_64/mkspecs/features/unix/opengl.prf:
../../Qt/5.14.1/gcc_64/mkspecs/features/uic.prf:
../../Qt/5.14.1/gcc_64/mkspecs/features/unix/thread.prf:
../../Qt/5.14.1/gcc_64/mkspecs/features/qmake_use.prf:
../../Qt/5.14.1/gcc_64/mkspecs/features/file_copies.prf:
../../Qt/5.14.1/gcc_64/mkspecs/features/testcase_targets.prf:
../../Qt/5.14.1/gcc_64/mkspecs/features/exceptions.prf:
../../Qt/5.14.1/gcc_64/mkspecs/features/yacc.prf:
../../Qt/5.14.1/gcc_64/mkspecs/features/lex.prf:
BRDF.pro:
qmake: FORCE
	@$(QMAKE) -o Makefile BRDF.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug

qmake_all: FORCE


all: Makefile brdf

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents ../../Qt/5.14.1/gcc_64/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents brdfdata.h glutcallbacks.h glut.h glext.h $(DISTDIR)/
	$(COPY_FILE) --parents brdfdata.cpp glutcallbacks.cpp main.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: ../../Qt/5.14.1/gcc_64/mkspecs/features/data/dummy.cpp
	g++ -pipe -std=c++11 -g -Wall -Wextra -dM -E -o moc_predefs.h ../../Qt/5.14.1/gcc_64/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all:
compiler_moc_header_clean:
compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean 

####### Compile

brdfdata.o: brdfdata.cpp brdfdata.h \
		../libigl/external/eigen/Eigen/Dense \
		../libigl/external/eigen/Eigen/Core \
		../libigl/external/eigen/Eigen/src/Core/util/DisableStupidWarnings.h \
		../libigl/external/eigen/Eigen/src/Core/util/Macros.h \
		../libigl/external/eigen/Eigen/src/Core/util/MKL_support.h \
		../libigl/external/eigen/Eigen/src/misc/blas.h \
		../libigl/external/eigen/Eigen/src/Core/util/Constants.h \
		../libigl/external/eigen/Eigen/src/Core/util/Meta.h \
		../libigl/external/eigen/Eigen/src/Core/util/ForwardDeclarations.h \
		../libigl/external/eigen/Eigen/src/Core/util/StaticAssert.h \
		../libigl/external/eigen/Eigen/src/Core/util/XprHelper.h \
		../libigl/external/eigen/Eigen/src/Core/util/Memory.h \
		../libigl/external/eigen/Eigen/src/Core/NumTraits.h \
		../libigl/external/eigen/Eigen/src/Core/MathFunctions.h \
		../libigl/external/eigen/Eigen/src/Core/GenericPacketMath.h \
		../libigl/external/eigen/Eigen/src/Core/MathFunctionsImpl.h \
		../libigl/external/eigen/Eigen/src/Core/arch/Default/ConjHelper.h \
		../libigl/external/eigen/Eigen/src/Core/arch/SSE/PacketMath.h \
		../libigl/external/eigen/Eigen/src/Core/arch/AVX/PacketMath.h \
		../libigl/external/eigen/Eigen/src/Core/arch/AVX512/PacketMath.h \
		../libigl/external/eigen/Eigen/src/Core/arch/AVX512/MathFunctions.h \
		../libigl/external/eigen/Eigen/src/Core/arch/SSE/Complex.h \
		../libigl/external/eigen/Eigen/src/Core/arch/SSE/MathFunctions.h \
		../libigl/external/eigen/Eigen/src/Core/arch/AVX/MathFunctions.h \
		../libigl/external/eigen/Eigen/src/Core/arch/AVX/Complex.h \
		../libigl/external/eigen/Eigen/src/Core/arch/AVX/TypeCasting.h \
		../libigl/external/eigen/Eigen/src/Core/arch/SSE/TypeCasting.h \
		../libigl/external/eigen/Eigen/src/Core/arch/AltiVec/PacketMath.h \
		../libigl/external/eigen/Eigen/src/Core/arch/AltiVec/MathFunctions.h \
		../libigl/external/eigen/Eigen/src/Core/arch/AltiVec/Complex.h \
		../libigl/external/eigen/Eigen/src/Core/arch/NEON/PacketMath.h \
		../libigl/external/eigen/Eigen/src/Core/arch/NEON/MathFunctions.h \
		../libigl/external/eigen/Eigen/src/Core/arch/NEON/Complex.h \
		../libigl/external/eigen/Eigen/src/Core/arch/ZVector/PacketMath.h \
		../libigl/external/eigen/Eigen/src/Core/arch/ZVector/MathFunctions.h \
		../libigl/external/eigen/Eigen/src/Core/arch/ZVector/Complex.h \
		../libigl/external/eigen/Eigen/src/Core/arch/CUDA/Half.h \
		../libigl/external/eigen/Eigen/src/Core/arch/CUDA/PacketMathHalf.h \
		../libigl/external/eigen/Eigen/src/Core/arch/CUDA/TypeCasting.h \
		../libigl/external/eigen/Eigen/src/Core/arch/CUDA/PacketMath.h \
		../libigl/external/eigen/Eigen/src/Core/arch/CUDA/MathFunctions.h \
		../libigl/external/eigen/Eigen/src/Core/arch/Default/Settings.h \
		../libigl/external/eigen/Eigen/src/Core/functors/TernaryFunctors.h \
		../libigl/external/eigen/Eigen/src/Core/functors/BinaryFunctors.h \
		../libigl/external/eigen/Eigen/src/Core/functors/UnaryFunctors.h \
		../libigl/external/eigen/Eigen/src/Core/functors/NullaryFunctors.h \
		../libigl/external/eigen/Eigen/src/Core/functors/StlFunctors.h \
		../libigl/external/eigen/Eigen/src/Core/functors/AssignmentFunctors.h \
		../libigl/external/eigen/Eigen/src/Core/arch/CUDA/Complex.h \
		../libigl/external/eigen/Eigen/src/Core/IO.h \
		../libigl/external/eigen/Eigen/src/Core/DenseCoeffsBase.h \
		../libigl/external/eigen/Eigen/src/Core/DenseBase.h \
		../libigl/external/eigen/Eigen/src/plugins/BlockMethods.h \
		../libigl/external/eigen/Eigen/src/Core/MatrixBase.h \
		../libigl/external/eigen/Eigen/src/plugins/CommonCwiseUnaryOps.h \
		../libigl/external/eigen/Eigen/src/plugins/CommonCwiseBinaryOps.h \
		../libigl/external/eigen/Eigen/src/plugins/MatrixCwiseUnaryOps.h \
		../libigl/external/eigen/Eigen/src/plugins/MatrixCwiseBinaryOps.h \
		../libigl/external/eigen/Eigen/src/Core/EigenBase.h \
		../libigl/external/eigen/Eigen/src/Core/Product.h \
		../libigl/external/eigen/Eigen/src/Core/CoreEvaluators.h \
		../libigl/external/eigen/Eigen/src/Core/AssignEvaluator.h \
		../libigl/external/eigen/Eigen/src/Core/Assign.h \
		../libigl/external/eigen/Eigen/src/Core/ArrayBase.h \
		../libigl/external/eigen/Eigen/src/plugins/ArrayCwiseUnaryOps.h \
		../libigl/external/eigen/Eigen/src/plugins/ArrayCwiseBinaryOps.h \
		../libigl/external/eigen/Eigen/src/Core/util/BlasUtil.h \
		../libigl/external/eigen/Eigen/src/Core/DenseStorage.h \
		../libigl/external/eigen/Eigen/src/Core/NestByValue.h \
		../libigl/external/eigen/Eigen/src/Core/ReturnByValue.h \
		../libigl/external/eigen/Eigen/src/Core/NoAlias.h \
		../libigl/external/eigen/Eigen/src/Core/PlainObjectBase.h \
		../libigl/external/eigen/Eigen/src/Core/Matrix.h \
		../libigl/external/eigen/Eigen/src/Core/Array.h \
		../libigl/external/eigen/Eigen/src/Core/CwiseTernaryOp.h \
		../libigl/external/eigen/Eigen/src/Core/CwiseBinaryOp.h \
		../libigl/external/eigen/Eigen/src/Core/CwiseUnaryOp.h \
		../libigl/external/eigen/Eigen/src/Core/CwiseNullaryOp.h \
		../libigl/external/eigen/Eigen/src/Core/CwiseUnaryView.h \
		../libigl/external/eigen/Eigen/src/Core/SelfCwiseBinaryOp.h \
		../libigl/external/eigen/Eigen/src/Core/Dot.h \
		../libigl/external/eigen/Eigen/src/Core/StableNorm.h \
		../libigl/external/eigen/Eigen/src/Core/Stride.h \
		../libigl/external/eigen/Eigen/src/Core/MapBase.h \
		../libigl/external/eigen/Eigen/src/Core/Map.h \
		../libigl/external/eigen/Eigen/src/Core/Ref.h \
		../libigl/external/eigen/Eigen/src/Core/Block.h \
		../libigl/external/eigen/Eigen/src/Core/VectorBlock.h \
		../libigl/external/eigen/Eigen/src/Core/Transpose.h \
		../libigl/external/eigen/Eigen/src/Core/DiagonalMatrix.h \
		../libigl/external/eigen/Eigen/src/Core/Diagonal.h \
		../libigl/external/eigen/Eigen/src/Core/DiagonalProduct.h \
		../libigl/external/eigen/Eigen/src/Core/Redux.h \
		../libigl/external/eigen/Eigen/src/Core/Visitor.h \
		../libigl/external/eigen/Eigen/src/Core/Fuzzy.h \
		../libigl/external/eigen/Eigen/src/Core/Swap.h \
		../libigl/external/eigen/Eigen/src/Core/CommaInitializer.h \
		../libigl/external/eigen/Eigen/src/Core/GeneralProduct.h \
		../libigl/external/eigen/Eigen/src/Core/Solve.h \
		../libigl/external/eigen/Eigen/src/Core/Inverse.h \
		../libigl/external/eigen/Eigen/src/Core/SolverBase.h \
		../libigl/external/eigen/Eigen/src/Core/PermutationMatrix.h \
		../libigl/external/eigen/Eigen/src/Core/Transpositions.h \
		../libigl/external/eigen/Eigen/src/Core/TriangularMatrix.h \
		../libigl/external/eigen/Eigen/src/Core/SelfAdjointView.h \
		../libigl/external/eigen/Eigen/src/Core/products/GeneralBlockPanelKernel.h \
		../libigl/external/eigen/Eigen/src/Core/products/Parallelizer.h \
		../libigl/external/eigen/Eigen/src/Core/ProductEvaluators.h \
		../libigl/external/eigen/Eigen/src/Core/products/GeneralMatrixVector.h \
		../libigl/external/eigen/Eigen/src/Core/products/GeneralMatrixMatrix.h \
		../libigl/external/eigen/Eigen/src/Core/SolveTriangular.h \
		../libigl/external/eigen/Eigen/src/Core/products/GeneralMatrixMatrixTriangular.h \
		../libigl/external/eigen/Eigen/src/Core/products/SelfadjointMatrixVector.h \
		../libigl/external/eigen/Eigen/src/Core/products/SelfadjointMatrixMatrix.h \
		../libigl/external/eigen/Eigen/src/Core/products/SelfadjointProduct.h \
		../libigl/external/eigen/Eigen/src/Core/products/SelfadjointRank2Update.h \
		../libigl/external/eigen/Eigen/src/Core/products/TriangularMatrixVector.h \
		../libigl/external/eigen/Eigen/src/Core/products/TriangularMatrixMatrix.h \
		../libigl/external/eigen/Eigen/src/Core/products/TriangularSolverMatrix.h \
		../libigl/external/eigen/Eigen/src/Core/products/TriangularSolverVector.h \
		../libigl/external/eigen/Eigen/src/Core/BandMatrix.h \
		../libigl/external/eigen/Eigen/src/Core/CoreIterators.h \
		../libigl/external/eigen/Eigen/src/Core/ConditionEstimator.h \
		../libigl/external/eigen/Eigen/src/Core/BooleanRedux.h \
		../libigl/external/eigen/Eigen/src/Core/Select.h \
		../libigl/external/eigen/Eigen/src/Core/VectorwiseOp.h \
		../libigl/external/eigen/Eigen/src/Core/Random.h \
		../libigl/external/eigen/Eigen/src/Core/Replicate.h \
		../libigl/external/eigen/Eigen/src/Core/Reverse.h \
		../libigl/external/eigen/Eigen/src/Core/ArrayWrapper.h \
		../libigl/external/eigen/Eigen/src/Core/products/GeneralMatrixMatrix_BLAS.h \
		../libigl/external/eigen/Eigen/src/Core/products/GeneralMatrixVector_BLAS.h \
		../libigl/external/eigen/Eigen/src/Core/products/GeneralMatrixMatrixTriangular_BLAS.h \
		../libigl/external/eigen/Eigen/src/Core/products/SelfadjointMatrixMatrix_BLAS.h \
		../libigl/external/eigen/Eigen/src/Core/products/SelfadjointMatrixVector_BLAS.h \
		../libigl/external/eigen/Eigen/src/Core/products/TriangularMatrixMatrix_BLAS.h \
		../libigl/external/eigen/Eigen/src/Core/products/TriangularMatrixVector_BLAS.h \
		../libigl/external/eigen/Eigen/src/Core/products/TriangularSolverMatrix_BLAS.h \
		../libigl/external/eigen/Eigen/src/Core/Assign_MKL.h \
		../libigl/external/eigen/Eigen/src/Core/GlobalFunctions.h \
		../libigl/external/eigen/Eigen/src/Core/util/ReenableStupidWarnings.h \
		../libigl/external/eigen/Eigen/LU \
		../libigl/external/eigen/Eigen/src/misc/Kernel.h \
		../libigl/external/eigen/Eigen/src/misc/Image.h \
		../libigl/external/eigen/Eigen/src/LU/FullPivLU.h \
		../libigl/external/eigen/Eigen/src/LU/PartialPivLU.h \
		../libigl/external/eigen/Eigen/src/misc/lapacke.h \
		../libigl/external/eigen/Eigen/src/misc/lapacke_mangling.h \
		../libigl/external/eigen/Eigen/src/LU/PartialPivLU_LAPACKE.h \
		../libigl/external/eigen/Eigen/src/LU/Determinant.h \
		../libigl/external/eigen/Eigen/src/LU/InverseImpl.h \
		../libigl/external/eigen/Eigen/src/LU/arch/Inverse_SSE.h \
		../libigl/external/eigen/Eigen/Cholesky \
		../libigl/external/eigen/Eigen/Jacobi \
		../libigl/external/eigen/Eigen/src/Jacobi/Jacobi.h \
		../libigl/external/eigen/Eigen/src/Cholesky/LLT.h \
		../libigl/external/eigen/Eigen/src/Cholesky/LDLT.h \
		../libigl/external/eigen/Eigen/src/Cholesky/LLT_LAPACKE.h \
		../libigl/external/eigen/Eigen/QR \
		../libigl/external/eigen/Eigen/Householder \
		../libigl/external/eigen/Eigen/src/Householder/Householder.h \
		../libigl/external/eigen/Eigen/src/Householder/HouseholderSequence.h \
		../libigl/external/eigen/Eigen/src/Householder/BlockHouseholder.h \
		../libigl/external/eigen/Eigen/src/QR/HouseholderQR.h \
		../libigl/external/eigen/Eigen/src/QR/FullPivHouseholderQR.h \
		../libigl/external/eigen/Eigen/src/QR/ColPivHouseholderQR.h \
		../libigl/external/eigen/Eigen/src/QR/CompleteOrthogonalDecomposition.h \
		../libigl/external/eigen/Eigen/src/QR/HouseholderQR_LAPACKE.h \
		../libigl/external/eigen/Eigen/src/QR/ColPivHouseholderQR_LAPACKE.h \
		../libigl/external/eigen/Eigen/SVD \
		../libigl/external/eigen/Eigen/src/misc/RealSvd2x2.h \
		../libigl/external/eigen/Eigen/src/SVD/UpperBidiagonalization.h \
		../libigl/external/eigen/Eigen/src/SVD/SVDBase.h \
		../libigl/external/eigen/Eigen/src/SVD/JacobiSVD.h \
		../libigl/external/eigen/Eigen/src/SVD/BDCSVD.h \
		../libigl/external/eigen/Eigen/src/SVD/JacobiSVD_LAPACKE.h \
		../libigl/external/eigen/Eigen/Geometry \
		../libigl/external/eigen/Eigen/src/Geometry/OrthoMethods.h \
		../libigl/external/eigen/Eigen/src/Geometry/EulerAngles.h \
		../libigl/external/eigen/Eigen/src/Geometry/Homogeneous.h \
		../libigl/external/eigen/Eigen/src/Geometry/RotationBase.h \
		../libigl/external/eigen/Eigen/src/Geometry/Rotation2D.h \
		../libigl/external/eigen/Eigen/src/Geometry/Quaternion.h \
		../libigl/external/eigen/Eigen/src/Geometry/AngleAxis.h \
		../libigl/external/eigen/Eigen/src/Geometry/Transform.h \
		../libigl/external/eigen/Eigen/src/Geometry/Translation.h \
		../libigl/external/eigen/Eigen/src/Geometry/Scaling.h \
		../libigl/external/eigen/Eigen/src/Geometry/Hyperplane.h \
		../libigl/external/eigen/Eigen/src/Geometry/ParametrizedLine.h \
		../libigl/external/eigen/Eigen/src/Geometry/AlignedBox.h \
		../libigl/external/eigen/Eigen/src/Geometry/Umeyama.h \
		../libigl/external/eigen/Eigen/src/Geometry/arch/Geometry_SSE.h \
		../libigl/external/eigen/Eigen/Eigenvalues \
		../libigl/external/eigen/Eigen/src/Eigenvalues/Tridiagonalization.h \
		../libigl/external/eigen/Eigen/src/Eigenvalues/RealSchur.h \
		../libigl/external/eigen/Eigen/src/Eigenvalues/HessenbergDecomposition.h \
		../libigl/external/eigen/Eigen/src/Eigenvalues/EigenSolver.h \
		../libigl/external/eigen/Eigen/src/Eigenvalues/SelfAdjointEigenSolver.h \
		../libigl/external/eigen/Eigen/src/Eigenvalues/GeneralizedSelfAdjointEigenSolver.h \
		../libigl/external/eigen/Eigen/src/Eigenvalues/ComplexSchur.h \
		../libigl/external/eigen/Eigen/src/Eigenvalues/ComplexEigenSolver.h \
		../libigl/external/eigen/Eigen/src/Eigenvalues/RealQZ.h \
		../libigl/external/eigen/Eigen/src/Eigenvalues/GeneralizedEigenSolver.h \
		../libigl/external/eigen/Eigen/src/Eigenvalues/MatrixBaseEigenvalues.h \
		../libigl/external/eigen/Eigen/src/Eigenvalues/RealSchur_LAPACKE.h \
		../libigl/external/eigen/Eigen/src/Eigenvalues/ComplexSchur_LAPACKE.h \
		../libigl/external/eigen/Eigen/src/Eigenvalues/SelfAdjointEigenSolver_LAPACKE.h \
		glut.h \
		levmar/levmar.h \
		../libigl/include/igl/readOBJ.h \
		../libigl/include/igl/igl_inline.h \
		../libigl/include/igl/readOBJ.cpp \
		../libigl/include/igl/list_to_matrix.h \
		../libigl/include/igl/list_to_matrix.cpp \
		../libigl/include/igl/max_size.h \
		../libigl/include/igl/max_size.cpp \
		../libigl/include/igl/min_size.h \
		../libigl/include/igl/min_size.cpp \
		../libigl/include/igl/barycentric_coordinates.h \
		../libigl/include/igl/barycentric_coordinates.cpp \
		../libigl/include/igl/volume.h \
		../libigl/include/igl/volume.cpp \
		../libigl/include/igl/cross.h \
		../libigl/include/igl/cross.cpp \
		../libigl/include/igl/point_mesh_squared_distance.h \
		../libigl/include/igl/point_mesh_squared_distance.cpp \
		../libigl/include/igl/AABB.h \
		../libigl/include/igl/Hit.h \
		../libigl/include/igl/AABB.cpp \
		../libigl/include/igl/EPS.h \
		../libigl/include/igl/EPS.cpp \
		../libigl/include/igl/barycenter.h \
		../libigl/include/igl/barycenter.cpp \
		../libigl/include/igl/colon.h \
		../libigl/include/igl/colon.cpp \
		../libigl/include/igl/LinSpaced.h \
		../libigl/include/igl/doublearea.h \
		../libigl/include/igl/doublearea.cpp \
		../libigl/include/igl/edge_lengths.h \
		../libigl/include/igl/edge_lengths.cpp \
		../libigl/include/igl/squared_edge_lengths.h \
		../libigl/include/igl/squared_edge_lengths.cpp \
		../libigl/include/igl/parallel_for.h \
		../libigl/include/igl/sort.h \
		../libigl/include/igl/sort.cpp \
		../libigl/include/igl/SortableRow.h \
		../libigl/include/igl/reorder.h \
		../libigl/include/igl/reorder.cpp \
		../libigl/include/igl/IndexComparison.h \
		../libigl/include/igl/point_simplex_squared_distance.h \
		../libigl/include/igl/point_simplex_squared_distance.cpp \
		../libigl/include/igl/project_to_line_segment.h \
		../libigl/include/igl/project_to_line_segment.cpp \
		../libigl/include/igl/project_to_line.h \
		../libigl/include/igl/project_to_line.cpp \
		../libigl/include/igl/ray_box_intersect.h \
		../libigl/include/igl/ray_box_intersect.cpp \
		../libigl/include/igl/ray_mesh_intersect.h \
		../libigl/include/igl/ray_mesh_intersect.cpp \
		../libigl/include/igl/raytri.c \
		../libigl/include/igl/voxel_grid.h \
		../libigl/include/igl/voxel_grid.cpp \
		../libigl/include/igl/grid.h \
		../libigl/include/igl/grid.cpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o brdfdata.o brdfdata.cpp

glutcallbacks.o: glutcallbacks.cpp brdfdata.h \
		../libigl/external/eigen/Eigen/Dense \
		../libigl/external/eigen/Eigen/Core \
		../libigl/external/eigen/Eigen/src/Core/util/DisableStupidWarnings.h \
		../libigl/external/eigen/Eigen/src/Core/util/Macros.h \
		../libigl/external/eigen/Eigen/src/Core/util/MKL_support.h \
		../libigl/external/eigen/Eigen/src/misc/blas.h \
		../libigl/external/eigen/Eigen/src/Core/util/Constants.h \
		../libigl/external/eigen/Eigen/src/Core/util/Meta.h \
		../libigl/external/eigen/Eigen/src/Core/util/ForwardDeclarations.h \
		../libigl/external/eigen/Eigen/src/Core/util/StaticAssert.h \
		../libigl/external/eigen/Eigen/src/Core/util/XprHelper.h \
		../libigl/external/eigen/Eigen/src/Core/util/Memory.h \
		../libigl/external/eigen/Eigen/src/Core/NumTraits.h \
		../libigl/external/eigen/Eigen/src/Core/MathFunctions.h \
		../libigl/external/eigen/Eigen/src/Core/GenericPacketMath.h \
		../libigl/external/eigen/Eigen/src/Core/MathFunctionsImpl.h \
		../libigl/external/eigen/Eigen/src/Core/arch/Default/ConjHelper.h \
		../libigl/external/eigen/Eigen/src/Core/arch/SSE/PacketMath.h \
		../libigl/external/eigen/Eigen/src/Core/arch/AVX/PacketMath.h \
		../libigl/external/eigen/Eigen/src/Core/arch/AVX512/PacketMath.h \
		../libigl/external/eigen/Eigen/src/Core/arch/AVX512/MathFunctions.h \
		../libigl/external/eigen/Eigen/src/Core/arch/SSE/Complex.h \
		../libigl/external/eigen/Eigen/src/Core/arch/SSE/MathFunctions.h \
		../libigl/external/eigen/Eigen/src/Core/arch/AVX/MathFunctions.h \
		../libigl/external/eigen/Eigen/src/Core/arch/AVX/Complex.h \
		../libigl/external/eigen/Eigen/src/Core/arch/AVX/TypeCasting.h \
		../libigl/external/eigen/Eigen/src/Core/arch/SSE/TypeCasting.h \
		../libigl/external/eigen/Eigen/src/Core/arch/AltiVec/PacketMath.h \
		../libigl/external/eigen/Eigen/src/Core/arch/AltiVec/MathFunctions.h \
		../libigl/external/eigen/Eigen/src/Core/arch/AltiVec/Complex.h \
		../libigl/external/eigen/Eigen/src/Core/arch/NEON/PacketMath.h \
		../libigl/external/eigen/Eigen/src/Core/arch/NEON/MathFunctions.h \
		../libigl/external/eigen/Eigen/src/Core/arch/NEON/Complex.h \
		../libigl/external/eigen/Eigen/src/Core/arch/ZVector/PacketMath.h \
		../libigl/external/eigen/Eigen/src/Core/arch/ZVector/MathFunctions.h \
		../libigl/external/eigen/Eigen/src/Core/arch/ZVector/Complex.h \
		../libigl/external/eigen/Eigen/src/Core/arch/CUDA/Half.h \
		../libigl/external/eigen/Eigen/src/Core/arch/CUDA/PacketMathHalf.h \
		../libigl/external/eigen/Eigen/src/Core/arch/CUDA/TypeCasting.h \
		../libigl/external/eigen/Eigen/src/Core/arch/CUDA/PacketMath.h \
		../libigl/external/eigen/Eigen/src/Core/arch/CUDA/MathFunctions.h \
		../libigl/external/eigen/Eigen/src/Core/arch/Default/Settings.h \
		../libigl/external/eigen/Eigen/src/Core/functors/TernaryFunctors.h \
		../libigl/external/eigen/Eigen/src/Core/functors/BinaryFunctors.h \
		../libigl/external/eigen/Eigen/src/Core/functors/UnaryFunctors.h \
		../libigl/external/eigen/Eigen/src/Core/functors/NullaryFunctors.h \
		../libigl/external/eigen/Eigen/src/Core/functors/StlFunctors.h \
		../libigl/external/eigen/Eigen/src/Core/functors/AssignmentFunctors.h \
		../libigl/external/eigen/Eigen/src/Core/arch/CUDA/Complex.h \
		../libigl/external/eigen/Eigen/src/Core/IO.h \
		../libigl/external/eigen/Eigen/src/Core/DenseCoeffsBase.h \
		../libigl/external/eigen/Eigen/src/Core/DenseBase.h \
		../libigl/external/eigen/Eigen/src/plugins/BlockMethods.h \
		../libigl/external/eigen/Eigen/src/Core/MatrixBase.h \
		../libigl/external/eigen/Eigen/src/plugins/CommonCwiseUnaryOps.h \
		../libigl/external/eigen/Eigen/src/plugins/CommonCwiseBinaryOps.h \
		../libigl/external/eigen/Eigen/src/plugins/MatrixCwiseUnaryOps.h \
		../libigl/external/eigen/Eigen/src/plugins/MatrixCwiseBinaryOps.h \
		../libigl/external/eigen/Eigen/src/Core/EigenBase.h \
		../libigl/external/eigen/Eigen/src/Core/Product.h \
		../libigl/external/eigen/Eigen/src/Core/CoreEvaluators.h \
		../libigl/external/eigen/Eigen/src/Core/AssignEvaluator.h \
		../libigl/external/eigen/Eigen/src/Core/Assign.h \
		../libigl/external/eigen/Eigen/src/Core/ArrayBase.h \
		../libigl/external/eigen/Eigen/src/plugins/ArrayCwiseUnaryOps.h \
		../libigl/external/eigen/Eigen/src/plugins/ArrayCwiseBinaryOps.h \
		../libigl/external/eigen/Eigen/src/Core/util/BlasUtil.h \
		../libigl/external/eigen/Eigen/src/Core/DenseStorage.h \
		../libigl/external/eigen/Eigen/src/Core/NestByValue.h \
		../libigl/external/eigen/Eigen/src/Core/ReturnByValue.h \
		../libigl/external/eigen/Eigen/src/Core/NoAlias.h \
		../libigl/external/eigen/Eigen/src/Core/PlainObjectBase.h \
		../libigl/external/eigen/Eigen/src/Core/Matrix.h \
		../libigl/external/eigen/Eigen/src/Core/Array.h \
		../libigl/external/eigen/Eigen/src/Core/CwiseTernaryOp.h \
		../libigl/external/eigen/Eigen/src/Core/CwiseBinaryOp.h \
		../libigl/external/eigen/Eigen/src/Core/CwiseUnaryOp.h \
		../libigl/external/eigen/Eigen/src/Core/CwiseNullaryOp.h \
		../libigl/external/eigen/Eigen/src/Core/CwiseUnaryView.h \
		../libigl/external/eigen/Eigen/src/Core/SelfCwiseBinaryOp.h \
		../libigl/external/eigen/Eigen/src/Core/Dot.h \
		../libigl/external/eigen/Eigen/src/Core/StableNorm.h \
		../libigl/external/eigen/Eigen/src/Core/Stride.h \
		../libigl/external/eigen/Eigen/src/Core/MapBase.h \
		../libigl/external/eigen/Eigen/src/Core/Map.h \
		../libigl/external/eigen/Eigen/src/Core/Ref.h \
		../libigl/external/eigen/Eigen/src/Core/Block.h \
		../libigl/external/eigen/Eigen/src/Core/VectorBlock.h \
		../libigl/external/eigen/Eigen/src/Core/Transpose.h \
		../libigl/external/eigen/Eigen/src/Core/DiagonalMatrix.h \
		../libigl/external/eigen/Eigen/src/Core/Diagonal.h \
		../libigl/external/eigen/Eigen/src/Core/DiagonalProduct.h \
		../libigl/external/eigen/Eigen/src/Core/Redux.h \
		../libigl/external/eigen/Eigen/src/Core/Visitor.h \
		../libigl/external/eigen/Eigen/src/Core/Fuzzy.h \
		../libigl/external/eigen/Eigen/src/Core/Swap.h \
		../libigl/external/eigen/Eigen/src/Core/CommaInitializer.h \
		../libigl/external/eigen/Eigen/src/Core/GeneralProduct.h \
		../libigl/external/eigen/Eigen/src/Core/Solve.h \
		../libigl/external/eigen/Eigen/src/Core/Inverse.h \
		../libigl/external/eigen/Eigen/src/Core/SolverBase.h \
		../libigl/external/eigen/Eigen/src/Core/PermutationMatrix.h \
		../libigl/external/eigen/Eigen/src/Core/Transpositions.h \
		../libigl/external/eigen/Eigen/src/Core/TriangularMatrix.h \
		../libigl/external/eigen/Eigen/src/Core/SelfAdjointView.h \
		../libigl/external/eigen/Eigen/src/Core/products/GeneralBlockPanelKernel.h \
		../libigl/external/eigen/Eigen/src/Core/products/Parallelizer.h \
		../libigl/external/eigen/Eigen/src/Core/ProductEvaluators.h \
		../libigl/external/eigen/Eigen/src/Core/products/GeneralMatrixVector.h \
		../libigl/external/eigen/Eigen/src/Core/products/GeneralMatrixMatrix.h \
		../libigl/external/eigen/Eigen/src/Core/SolveTriangular.h \
		../libigl/external/eigen/Eigen/src/Core/products/GeneralMatrixMatrixTriangular.h \
		../libigl/external/eigen/Eigen/src/Core/products/SelfadjointMatrixVector.h \
		../libigl/external/eigen/Eigen/src/Core/products/SelfadjointMatrixMatrix.h \
		../libigl/external/eigen/Eigen/src/Core/products/SelfadjointProduct.h \
		../libigl/external/eigen/Eigen/src/Core/products/SelfadjointRank2Update.h \
		../libigl/external/eigen/Eigen/src/Core/products/TriangularMatrixVector.h \
		../libigl/external/eigen/Eigen/src/Core/products/TriangularMatrixMatrix.h \
		../libigl/external/eigen/Eigen/src/Core/products/TriangularSolverMatrix.h \
		../libigl/external/eigen/Eigen/src/Core/products/TriangularSolverVector.h \
		../libigl/external/eigen/Eigen/src/Core/BandMatrix.h \
		../libigl/external/eigen/Eigen/src/Core/CoreIterators.h \
		../libigl/external/eigen/Eigen/src/Core/ConditionEstimator.h \
		../libigl/external/eigen/Eigen/src/Core/BooleanRedux.h \
		../libigl/external/eigen/Eigen/src/Core/Select.h \
		../libigl/external/eigen/Eigen/src/Core/VectorwiseOp.h \
		../libigl/external/eigen/Eigen/src/Core/Random.h \
		../libigl/external/eigen/Eigen/src/Core/Replicate.h \
		../libigl/external/eigen/Eigen/src/Core/Reverse.h \
		../libigl/external/eigen/Eigen/src/Core/ArrayWrapper.h \
		../libigl/external/eigen/Eigen/src/Core/products/GeneralMatrixMatrix_BLAS.h \
		../libigl/external/eigen/Eigen/src/Core/products/GeneralMatrixVector_BLAS.h \
		../libigl/external/eigen/Eigen/src/Core/products/GeneralMatrixMatrixTriangular_BLAS.h \
		../libigl/external/eigen/Eigen/src/Core/products/SelfadjointMatrixMatrix_BLAS.h \
		../libigl/external/eigen/Eigen/src/Core/products/SelfadjointMatrixVector_BLAS.h \
		../libigl/external/eigen/Eigen/src/Core/products/TriangularMatrixMatrix_BLAS.h \
		../libigl/external/eigen/Eigen/src/Core/products/TriangularMatrixVector_BLAS.h \
		../libigl/external/eigen/Eigen/src/Core/products/TriangularSolverMatrix_BLAS.h \
		../libigl/external/eigen/Eigen/src/Core/Assign_MKL.h \
		../libigl/external/eigen/Eigen/src/Core/GlobalFunctions.h \
		../libigl/external/eigen/Eigen/src/Core/util/ReenableStupidWarnings.h \
		../libigl/external/eigen/Eigen/LU \
		../libigl/external/eigen/Eigen/src/misc/Kernel.h \
		../libigl/external/eigen/Eigen/src/misc/Image.h \
		../libigl/external/eigen/Eigen/src/LU/FullPivLU.h \
		../libigl/external/eigen/Eigen/src/LU/PartialPivLU.h \
		../libigl/external/eigen/Eigen/src/misc/lapacke.h \
		../libigl/external/eigen/Eigen/src/misc/lapacke_mangling.h \
		../libigl/external/eigen/Eigen/src/LU/PartialPivLU_LAPACKE.h \
		../libigl/external/eigen/Eigen/src/LU/Determinant.h \
		../libigl/external/eigen/Eigen/src/LU/InverseImpl.h \
		../libigl/external/eigen/Eigen/src/LU/arch/Inverse_SSE.h \
		../libigl/external/eigen/Eigen/Cholesky \
		../libigl/external/eigen/Eigen/Jacobi \
		../libigl/external/eigen/Eigen/src/Jacobi/Jacobi.h \
		../libigl/external/eigen/Eigen/src/Cholesky/LLT.h \
		../libigl/external/eigen/Eigen/src/Cholesky/LDLT.h \
		../libigl/external/eigen/Eigen/src/Cholesky/LLT_LAPACKE.h \
		../libigl/external/eigen/Eigen/QR \
		../libigl/external/eigen/Eigen/Householder \
		../libigl/external/eigen/Eigen/src/Householder/Householder.h \
		../libigl/external/eigen/Eigen/src/Householder/HouseholderSequence.h \
		../libigl/external/eigen/Eigen/src/Householder/BlockHouseholder.h \
		../libigl/external/eigen/Eigen/src/QR/HouseholderQR.h \
		../libigl/external/eigen/Eigen/src/QR/FullPivHouseholderQR.h \
		../libigl/external/eigen/Eigen/src/QR/ColPivHouseholderQR.h \
		../libigl/external/eigen/Eigen/src/QR/CompleteOrthogonalDecomposition.h \
		../libigl/external/eigen/Eigen/src/QR/HouseholderQR_LAPACKE.h \
		../libigl/external/eigen/Eigen/src/QR/ColPivHouseholderQR_LAPACKE.h \
		../libigl/external/eigen/Eigen/SVD \
		../libigl/external/eigen/Eigen/src/misc/RealSvd2x2.h \
		../libigl/external/eigen/Eigen/src/SVD/UpperBidiagonalization.h \
		../libigl/external/eigen/Eigen/src/SVD/SVDBase.h \
		../libigl/external/eigen/Eigen/src/SVD/JacobiSVD.h \
		../libigl/external/eigen/Eigen/src/SVD/BDCSVD.h \
		../libigl/external/eigen/Eigen/src/SVD/JacobiSVD_LAPACKE.h \
		../libigl/external/eigen/Eigen/Geometry \
		../libigl/external/eigen/Eigen/src/Geometry/OrthoMethods.h \
		../libigl/external/eigen/Eigen/src/Geometry/EulerAngles.h \
		../libigl/external/eigen/Eigen/src/Geometry/Homogeneous.h \
		../libigl/external/eigen/Eigen/src/Geometry/RotationBase.h \
		../libigl/external/eigen/Eigen/src/Geometry/Rotation2D.h \
		../libigl/external/eigen/Eigen/src/Geometry/Quaternion.h \
		../libigl/external/eigen/Eigen/src/Geometry/AngleAxis.h \
		../libigl/external/eigen/Eigen/src/Geometry/Transform.h \
		../libigl/external/eigen/Eigen/src/Geometry/Translation.h \
		../libigl/external/eigen/Eigen/src/Geometry/Scaling.h \
		../libigl/external/eigen/Eigen/src/Geometry/Hyperplane.h \
		../libigl/external/eigen/Eigen/src/Geometry/ParametrizedLine.h \
		../libigl/external/eigen/Eigen/src/Geometry/AlignedBox.h \
		../libigl/external/eigen/Eigen/src/Geometry/Umeyama.h \
		../libigl/external/eigen/Eigen/src/Geometry/arch/Geometry_SSE.h \
		../libigl/external/eigen/Eigen/Eigenvalues \
		../libigl/external/eigen/Eigen/src/Eigenvalues/Tridiagonalization.h \
		../libigl/external/eigen/Eigen/src/Eigenvalues/RealSchur.h \
		../libigl/external/eigen/Eigen/src/Eigenvalues/HessenbergDecomposition.h \
		../libigl/external/eigen/Eigen/src/Eigenvalues/EigenSolver.h \
		../libigl/external/eigen/Eigen/src/Eigenvalues/SelfAdjointEigenSolver.h \
		../libigl/external/eigen/Eigen/src/Eigenvalues/GeneralizedSelfAdjointEigenSolver.h \
		../libigl/external/eigen/Eigen/src/Eigenvalues/ComplexSchur.h \
		../libigl/external/eigen/Eigen/src/Eigenvalues/ComplexEigenSolver.h \
		../libigl/external/eigen/Eigen/src/Eigenvalues/RealQZ.h \
		../libigl/external/eigen/Eigen/src/Eigenvalues/GeneralizedEigenSolver.h \
		../libigl/external/eigen/Eigen/src/Eigenvalues/MatrixBaseEigenvalues.h \
		../libigl/external/eigen/Eigen/src/Eigenvalues/RealSchur_LAPACKE.h \
		../libigl/external/eigen/Eigen/src/Eigenvalues/ComplexSchur_LAPACKE.h \
		../libigl/external/eigen/Eigen/src/Eigenvalues/SelfAdjointEigenSolver_LAPACKE.h \
		glutcallbacks.h \
		glut.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o glutcallbacks.o glutcallbacks.cpp

main.o: main.cpp brdfdata.h \
		../libigl/external/eigen/Eigen/Dense \
		../libigl/external/eigen/Eigen/Core \
		../libigl/external/eigen/Eigen/src/Core/util/DisableStupidWarnings.h \
		../libigl/external/eigen/Eigen/src/Core/util/Macros.h \
		../libigl/external/eigen/Eigen/src/Core/util/MKL_support.h \
		../libigl/external/eigen/Eigen/src/misc/blas.h \
		../libigl/external/eigen/Eigen/src/Core/util/Constants.h \
		../libigl/external/eigen/Eigen/src/Core/util/Meta.h \
		../libigl/external/eigen/Eigen/src/Core/util/ForwardDeclarations.h \
		../libigl/external/eigen/Eigen/src/Core/util/StaticAssert.h \
		../libigl/external/eigen/Eigen/src/Core/util/XprHelper.h \
		../libigl/external/eigen/Eigen/src/Core/util/Memory.h \
		../libigl/external/eigen/Eigen/src/Core/NumTraits.h \
		../libigl/external/eigen/Eigen/src/Core/MathFunctions.h \
		../libigl/external/eigen/Eigen/src/Core/GenericPacketMath.h \
		../libigl/external/eigen/Eigen/src/Core/MathFunctionsImpl.h \
		../libigl/external/eigen/Eigen/src/Core/arch/Default/ConjHelper.h \
		../libigl/external/eigen/Eigen/src/Core/arch/SSE/PacketMath.h \
		../libigl/external/eigen/Eigen/src/Core/arch/AVX/PacketMath.h \
		../libigl/external/eigen/Eigen/src/Core/arch/AVX512/PacketMath.h \
		../libigl/external/eigen/Eigen/src/Core/arch/AVX512/MathFunctions.h \
		../libigl/external/eigen/Eigen/src/Core/arch/SSE/Complex.h \
		../libigl/external/eigen/Eigen/src/Core/arch/SSE/MathFunctions.h \
		../libigl/external/eigen/Eigen/src/Core/arch/AVX/MathFunctions.h \
		../libigl/external/eigen/Eigen/src/Core/arch/AVX/Complex.h \
		../libigl/external/eigen/Eigen/src/Core/arch/AVX/TypeCasting.h \
		../libigl/external/eigen/Eigen/src/Core/arch/SSE/TypeCasting.h \
		../libigl/external/eigen/Eigen/src/Core/arch/AltiVec/PacketMath.h \
		../libigl/external/eigen/Eigen/src/Core/arch/AltiVec/MathFunctions.h \
		../libigl/external/eigen/Eigen/src/Core/arch/AltiVec/Complex.h \
		../libigl/external/eigen/Eigen/src/Core/arch/NEON/PacketMath.h \
		../libigl/external/eigen/Eigen/src/Core/arch/NEON/MathFunctions.h \
		../libigl/external/eigen/Eigen/src/Core/arch/NEON/Complex.h \
		../libigl/external/eigen/Eigen/src/Core/arch/ZVector/PacketMath.h \
		../libigl/external/eigen/Eigen/src/Core/arch/ZVector/MathFunctions.h \
		../libigl/external/eigen/Eigen/src/Core/arch/ZVector/Complex.h \
		../libigl/external/eigen/Eigen/src/Core/arch/CUDA/Half.h \
		../libigl/external/eigen/Eigen/src/Core/arch/CUDA/PacketMathHalf.h \
		../libigl/external/eigen/Eigen/src/Core/arch/CUDA/TypeCasting.h \
		../libigl/external/eigen/Eigen/src/Core/arch/CUDA/PacketMath.h \
		../libigl/external/eigen/Eigen/src/Core/arch/CUDA/MathFunctions.h \
		../libigl/external/eigen/Eigen/src/Core/arch/Default/Settings.h \
		../libigl/external/eigen/Eigen/src/Core/functors/TernaryFunctors.h \
		../libigl/external/eigen/Eigen/src/Core/functors/BinaryFunctors.h \
		../libigl/external/eigen/Eigen/src/Core/functors/UnaryFunctors.h \
		../libigl/external/eigen/Eigen/src/Core/functors/NullaryFunctors.h \
		../libigl/external/eigen/Eigen/src/Core/functors/StlFunctors.h \
		../libigl/external/eigen/Eigen/src/Core/functors/AssignmentFunctors.h \
		../libigl/external/eigen/Eigen/src/Core/arch/CUDA/Complex.h \
		../libigl/external/eigen/Eigen/src/Core/IO.h \
		../libigl/external/eigen/Eigen/src/Core/DenseCoeffsBase.h \
		../libigl/external/eigen/Eigen/src/Core/DenseBase.h \
		../libigl/external/eigen/Eigen/src/plugins/BlockMethods.h \
		../libigl/external/eigen/Eigen/src/Core/MatrixBase.h \
		../libigl/external/eigen/Eigen/src/plugins/CommonCwiseUnaryOps.h \
		../libigl/external/eigen/Eigen/src/plugins/CommonCwiseBinaryOps.h \
		../libigl/external/eigen/Eigen/src/plugins/MatrixCwiseUnaryOps.h \
		../libigl/external/eigen/Eigen/src/plugins/MatrixCwiseBinaryOps.h \
		../libigl/external/eigen/Eigen/src/Core/EigenBase.h \
		../libigl/external/eigen/Eigen/src/Core/Product.h \
		../libigl/external/eigen/Eigen/src/Core/CoreEvaluators.h \
		../libigl/external/eigen/Eigen/src/Core/AssignEvaluator.h \
		../libigl/external/eigen/Eigen/src/Core/Assign.h \
		../libigl/external/eigen/Eigen/src/Core/ArrayBase.h \
		../libigl/external/eigen/Eigen/src/plugins/ArrayCwiseUnaryOps.h \
		../libigl/external/eigen/Eigen/src/plugins/ArrayCwiseBinaryOps.h \
		../libigl/external/eigen/Eigen/src/Core/util/BlasUtil.h \
		../libigl/external/eigen/Eigen/src/Core/DenseStorage.h \
		../libigl/external/eigen/Eigen/src/Core/NestByValue.h \
		../libigl/external/eigen/Eigen/src/Core/ReturnByValue.h \
		../libigl/external/eigen/Eigen/src/Core/NoAlias.h \
		../libigl/external/eigen/Eigen/src/Core/PlainObjectBase.h \
		../libigl/external/eigen/Eigen/src/Core/Matrix.h \
		../libigl/external/eigen/Eigen/src/Core/Array.h \
		../libigl/external/eigen/Eigen/src/Core/CwiseTernaryOp.h \
		../libigl/external/eigen/Eigen/src/Core/CwiseBinaryOp.h \
		../libigl/external/eigen/Eigen/src/Core/CwiseUnaryOp.h \
		../libigl/external/eigen/Eigen/src/Core/CwiseNullaryOp.h \
		../libigl/external/eigen/Eigen/src/Core/CwiseUnaryView.h \
		../libigl/external/eigen/Eigen/src/Core/SelfCwiseBinaryOp.h \
		../libigl/external/eigen/Eigen/src/Core/Dot.h \
		../libigl/external/eigen/Eigen/src/Core/StableNorm.h \
		../libigl/external/eigen/Eigen/src/Core/Stride.h \
		../libigl/external/eigen/Eigen/src/Core/MapBase.h \
		../libigl/external/eigen/Eigen/src/Core/Map.h \
		../libigl/external/eigen/Eigen/src/Core/Ref.h \
		../libigl/external/eigen/Eigen/src/Core/Block.h \
		../libigl/external/eigen/Eigen/src/Core/VectorBlock.h \
		../libigl/external/eigen/Eigen/src/Core/Transpose.h \
		../libigl/external/eigen/Eigen/src/Core/DiagonalMatrix.h \
		../libigl/external/eigen/Eigen/src/Core/Diagonal.h \
		../libigl/external/eigen/Eigen/src/Core/DiagonalProduct.h \
		../libigl/external/eigen/Eigen/src/Core/Redux.h \
		../libigl/external/eigen/Eigen/src/Core/Visitor.h \
		../libigl/external/eigen/Eigen/src/Core/Fuzzy.h \
		../libigl/external/eigen/Eigen/src/Core/Swap.h \
		../libigl/external/eigen/Eigen/src/Core/CommaInitializer.h \
		../libigl/external/eigen/Eigen/src/Core/GeneralProduct.h \
		../libigl/external/eigen/Eigen/src/Core/Solve.h \
		../libigl/external/eigen/Eigen/src/Core/Inverse.h \
		../libigl/external/eigen/Eigen/src/Core/SolverBase.h \
		../libigl/external/eigen/Eigen/src/Core/PermutationMatrix.h \
		../libigl/external/eigen/Eigen/src/Core/Transpositions.h \
		../libigl/external/eigen/Eigen/src/Core/TriangularMatrix.h \
		../libigl/external/eigen/Eigen/src/Core/SelfAdjointView.h \
		../libigl/external/eigen/Eigen/src/Core/products/GeneralBlockPanelKernel.h \
		../libigl/external/eigen/Eigen/src/Core/products/Parallelizer.h \
		../libigl/external/eigen/Eigen/src/Core/ProductEvaluators.h \
		../libigl/external/eigen/Eigen/src/Core/products/GeneralMatrixVector.h \
		../libigl/external/eigen/Eigen/src/Core/products/GeneralMatrixMatrix.h \
		../libigl/external/eigen/Eigen/src/Core/SolveTriangular.h \
		../libigl/external/eigen/Eigen/src/Core/products/GeneralMatrixMatrixTriangular.h \
		../libigl/external/eigen/Eigen/src/Core/products/SelfadjointMatrixVector.h \
		../libigl/external/eigen/Eigen/src/Core/products/SelfadjointMatrixMatrix.h \
		../libigl/external/eigen/Eigen/src/Core/products/SelfadjointProduct.h \
		../libigl/external/eigen/Eigen/src/Core/products/SelfadjointRank2Update.h \
		../libigl/external/eigen/Eigen/src/Core/products/TriangularMatrixVector.h \
		../libigl/external/eigen/Eigen/src/Core/products/TriangularMatrixMatrix.h \
		../libigl/external/eigen/Eigen/src/Core/products/TriangularSolverMatrix.h \
		../libigl/external/eigen/Eigen/src/Core/products/TriangularSolverVector.h \
		../libigl/external/eigen/Eigen/src/Core/BandMatrix.h \
		../libigl/external/eigen/Eigen/src/Core/CoreIterators.h \
		../libigl/external/eigen/Eigen/src/Core/ConditionEstimator.h \
		../libigl/external/eigen/Eigen/src/Core/BooleanRedux.h \
		../libigl/external/eigen/Eigen/src/Core/Select.h \
		../libigl/external/eigen/Eigen/src/Core/VectorwiseOp.h \
		../libigl/external/eigen/Eigen/src/Core/Random.h \
		../libigl/external/eigen/Eigen/src/Core/Replicate.h \
		../libigl/external/eigen/Eigen/src/Core/Reverse.h \
		../libigl/external/eigen/Eigen/src/Core/ArrayWrapper.h \
		../libigl/external/eigen/Eigen/src/Core/products/GeneralMatrixMatrix_BLAS.h \
		../libigl/external/eigen/Eigen/src/Core/products/GeneralMatrixVector_BLAS.h \
		../libigl/external/eigen/Eigen/src/Core/products/GeneralMatrixMatrixTriangular_BLAS.h \
		../libigl/external/eigen/Eigen/src/Core/products/SelfadjointMatrixMatrix_BLAS.h \
		../libigl/external/eigen/Eigen/src/Core/products/SelfadjointMatrixVector_BLAS.h \
		../libigl/external/eigen/Eigen/src/Core/products/TriangularMatrixMatrix_BLAS.h \
		../libigl/external/eigen/Eigen/src/Core/products/TriangularMatrixVector_BLAS.h \
		../libigl/external/eigen/Eigen/src/Core/products/TriangularSolverMatrix_BLAS.h \
		../libigl/external/eigen/Eigen/src/Core/Assign_MKL.h \
		../libigl/external/eigen/Eigen/src/Core/GlobalFunctions.h \
		../libigl/external/eigen/Eigen/src/Core/util/ReenableStupidWarnings.h \
		../libigl/external/eigen/Eigen/LU \
		../libigl/external/eigen/Eigen/src/misc/Kernel.h \
		../libigl/external/eigen/Eigen/src/misc/Image.h \
		../libigl/external/eigen/Eigen/src/LU/FullPivLU.h \
		../libigl/external/eigen/Eigen/src/LU/PartialPivLU.h \
		../libigl/external/eigen/Eigen/src/misc/lapacke.h \
		../libigl/external/eigen/Eigen/src/misc/lapacke_mangling.h \
		../libigl/external/eigen/Eigen/src/LU/PartialPivLU_LAPACKE.h \
		../libigl/external/eigen/Eigen/src/LU/Determinant.h \
		../libigl/external/eigen/Eigen/src/LU/InverseImpl.h \
		../libigl/external/eigen/Eigen/src/LU/arch/Inverse_SSE.h \
		../libigl/external/eigen/Eigen/Cholesky \
		../libigl/external/eigen/Eigen/Jacobi \
		../libigl/external/eigen/Eigen/src/Jacobi/Jacobi.h \
		../libigl/external/eigen/Eigen/src/Cholesky/LLT.h \
		../libigl/external/eigen/Eigen/src/Cholesky/LDLT.h \
		../libigl/external/eigen/Eigen/src/Cholesky/LLT_LAPACKE.h \
		../libigl/external/eigen/Eigen/QR \
		../libigl/external/eigen/Eigen/Householder \
		../libigl/external/eigen/Eigen/src/Householder/Householder.h \
		../libigl/external/eigen/Eigen/src/Householder/HouseholderSequence.h \
		../libigl/external/eigen/Eigen/src/Householder/BlockHouseholder.h \
		../libigl/external/eigen/Eigen/src/QR/HouseholderQR.h \
		../libigl/external/eigen/Eigen/src/QR/FullPivHouseholderQR.h \
		../libigl/external/eigen/Eigen/src/QR/ColPivHouseholderQR.h \
		../libigl/external/eigen/Eigen/src/QR/CompleteOrthogonalDecomposition.h \
		../libigl/external/eigen/Eigen/src/QR/HouseholderQR_LAPACKE.h \
		../libigl/external/eigen/Eigen/src/QR/ColPivHouseholderQR_LAPACKE.h \
		../libigl/external/eigen/Eigen/SVD \
		../libigl/external/eigen/Eigen/src/misc/RealSvd2x2.h \
		../libigl/external/eigen/Eigen/src/SVD/UpperBidiagonalization.h \
		../libigl/external/eigen/Eigen/src/SVD/SVDBase.h \
		../libigl/external/eigen/Eigen/src/SVD/JacobiSVD.h \
		../libigl/external/eigen/Eigen/src/SVD/BDCSVD.h \
		../libigl/external/eigen/Eigen/src/SVD/JacobiSVD_LAPACKE.h \
		../libigl/external/eigen/Eigen/Geometry \
		../libigl/external/eigen/Eigen/src/Geometry/OrthoMethods.h \
		../libigl/external/eigen/Eigen/src/Geometry/EulerAngles.h \
		../libigl/external/eigen/Eigen/src/Geometry/Homogeneous.h \
		../libigl/external/eigen/Eigen/src/Geometry/RotationBase.h \
		../libigl/external/eigen/Eigen/src/Geometry/Rotation2D.h \
		../libigl/external/eigen/Eigen/src/Geometry/Quaternion.h \
		../libigl/external/eigen/Eigen/src/Geometry/AngleAxis.h \
		../libigl/external/eigen/Eigen/src/Geometry/Transform.h \
		../libigl/external/eigen/Eigen/src/Geometry/Translation.h \
		../libigl/external/eigen/Eigen/src/Geometry/Scaling.h \
		../libigl/external/eigen/Eigen/src/Geometry/Hyperplane.h \
		../libigl/external/eigen/Eigen/src/Geometry/ParametrizedLine.h \
		../libigl/external/eigen/Eigen/src/Geometry/AlignedBox.h \
		../libigl/external/eigen/Eigen/src/Geometry/Umeyama.h \
		../libigl/external/eigen/Eigen/src/Geometry/arch/Geometry_SSE.h \
		../libigl/external/eigen/Eigen/Eigenvalues \
		../libigl/external/eigen/Eigen/src/Eigenvalues/Tridiagonalization.h \
		../libigl/external/eigen/Eigen/src/Eigenvalues/RealSchur.h \
		../libigl/external/eigen/Eigen/src/Eigenvalues/HessenbergDecomposition.h \
		../libigl/external/eigen/Eigen/src/Eigenvalues/EigenSolver.h \
		../libigl/external/eigen/Eigen/src/Eigenvalues/SelfAdjointEigenSolver.h \
		../libigl/external/eigen/Eigen/src/Eigenvalues/GeneralizedSelfAdjointEigenSolver.h \
		../libigl/external/eigen/Eigen/src/Eigenvalues/ComplexSchur.h \
		../libigl/external/eigen/Eigen/src/Eigenvalues/ComplexEigenSolver.h \
		../libigl/external/eigen/Eigen/src/Eigenvalues/RealQZ.h \
		../libigl/external/eigen/Eigen/src/Eigenvalues/GeneralizedEigenSolver.h \
		../libigl/external/eigen/Eigen/src/Eigenvalues/MatrixBaseEigenvalues.h \
		../libigl/external/eigen/Eigen/src/Eigenvalues/RealSchur_LAPACKE.h \
		../libigl/external/eigen/Eigen/src/Eigenvalues/ComplexSchur_LAPACKE.h \
		../libigl/external/eigen/Eigen/src/Eigenvalues/SelfAdjointEigenSolver_LAPACKE.h \
		glut.h \
		glutcallbacks.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

